# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:   
    - name: Generate build number
      uses: einaregilsson/build-number@v3
      with:
        token: ${{secrets.github_token}}        
    - name: Print new build number
      id: vars
      run: |
        echo "Build number is $BUILD_NUMBER"
        set-output name=docker_tag::$BUILD_NUMBER
        Build_Number=$BUILD_NUMBER
        echo "Build number is {{ steps.vars.outputs.docker_tag }}"
    - uses: actions/checkout@v2
    - name: first check
      run: |
        echo "value is $Build_Number"
        echo "value is ${{ env.Build_Number }}"
        echo "value is ${{ steps.vars.outputs.docker_tag }}"
        ls
        pwd
        cat values.yaml
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "image"
        replace: "world"
        include: "**values.yaml"
    - name: final check
      run: |
        ls
        pwd
        cat values.yaml
        
    - name: Checkout Project rebob
      uses: actions/checkout@master
      with: 
         repository: VkasSharma/repob
         token: ${{ secrets.ACTIONS_TOKEN }}
         path: ./repob
    - name: check repob content
      run: |
        cat ./repob/file
        ls ./repob
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "harbor.example.com/nsp_redis-exporter:v1.9.0"
        replace: "harbor.example.com/nsp_redis-exporter:${{env.Build_Number}}"
        include: "**file"
    - name: check repob content
      run: |
        ls
        cat ./repob/file     
        
